### ISSUE TITLE
Chunk visualization

### ISSUE THREAD

**Issue by txsmith** [preview-code/rite-evaluation#90]
- Write section in report what the visualization must do
- Investigate options and list in report the alternatives

**Comment by TimvdLippe** [comment]
In the meeting with Alberto we discussed several possibilities and native canvas drawing turned out to be the most feasible for now. This allows us to implement it the way we want and we can update it with Javascript quite easily.

A working example with dragging of an image is shown here: http://jsfiddle.net/QZejF/901/
